# Generated by Django 4.1.4 on 2023-04-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
